### ISSUE TITLE
not working with new version

### ISSUE THREAD

**Issue by nagim** [andrewrynhard/atom-git-gui#2]
Hi,

The package is not working with the latest atom version (1.10.2) even after rebuild.
Win 7 Pro 64-bit-

Stack trace:

```
TypeError: Cannot read property 'name' of null
    at processExports (C:\Users\username\.atom\packages\git-gui\node_modules\promisify-node\index.js:31:21)
    at processExports (C:\Users\username\.atom\packages\git-gui\node_modules\promisify-node\index.js:37:26)
    at processExports (C:\Users\username\.atom\packages\git-gui\node_modules\promisify-node\index.js:37:26)
    at processExports (C:\Users\username\.atom\packages\git-gui\node_modules\promisify-node\index.js:37:26)
    at processExports (C:\Users\username\.atom\packages\git-gui\node_modules\promisify-node\index.js:37:26)
    at processExports (C:\Users\username\.atom\packages\git-gui\node_modules\promisify-node\index.js:37:26)
    at module.exports (C:\Users\username\.atom\packages\git-gui\node_modules\promisify-node\index.js:112:10)
    at Object.<anonymous> (C:\Users\username\.atom\packages\git-gui\node_modules\nodegit\dist\nodegit.js:27:34)
    at Module._compile (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/username/.atom/packages/git-gui/lib/git-gui-action-bar-view.coffee:1:7)
    at Object.<anonymous> (file:///C:/Users/username/.atom/packages/git-gui/lib/git-gui-action-bar-view.coffee:1:1)
    at Module._compile (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/username/.atom/packages/git-gui/lib/git-gui-view.coffee:5:23)
    at Object.<anonymous> (file:///C:/Users/username/.atom/packages/git-gui/lib/git-gui-view.coffee:1:1)
    at Module._compile (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/username/.atom/packages/git-gui/lib/git-gui.coffee:1:14)
    at Object.<anonymous> (file:///C:/Users/username/.atom/packages/git-gui/lib/git-gui.coffee:1:1)
    at Module._compile (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:718:27)
    at Package.module.exports.Package.activateNow (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:798:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\username\AppData\Local\atom\app-1.10.2\resources\app.asar\src\window-event-handler.js:3:61)
```

Thanks!

**Comment by andrewrynhard** [comment]
@nagim this is happening when trying to toggle the package or install?

**Comment by nagim** [comment]
When toggling.

**Comment by andrewrynhard** [comment]
Hmm, working on Windows 10. I will have to find a Windows 7 machine. Was this after an Atom update or an update to the package?

**Comment by nagim** [comment]
I installed git-gui, then atom prompted to rebuild the packages, which I did, and restarted atom. After restart, tried to toggle it, that's when the error came up.

**Comment by andrewrynhard** [comment]
Awesome, thanks. Looking into it.

**Comment by andrewrynhard** [comment]
Looks like an issue with promisify-node. I have submitted an issue:
    https://github.com/nodegit/promisify-node/issues/24

**Comment by nagim** [comment]
Thanks a lot!

**Comment by andrewrynhard** [comment]
@nagim I have updated the package dependencies. If you are still interested in using this package, please try another install.

**Comment by andrewrynhard** [comment]
Closing this issue, feel free to open again.

**Comment by nagim** [comment]
Sorry for the delay in answering. I tested it and still not working, but most likely it's a local issue.

**Comment by andrewrynhard** [comment]
Interesting, ok I will reopen in case others run into the same issue.
